version: '3'

networks:
  docker-rede:

services:
  redis:
    container_name: redis
    image: redis:alpine
    ports: 
      - 6379:6379
    networks:
      - docker-rede
    
  postgres:
    container_name: postgres
    image: postgres:alpine
    volumes:
      - ./compras.sql:/docker-entrypoint-initdb.d/001_compras.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - docker-rede
      
  mongo: 
    container_name: mongo
    image: mongo:latest
    ports: 
      - 27017:27017
    networks:
      - docker-rede
      
  node:
    container_name: node
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
      - mongo
    command: sh -c "cd /app && npm install && node src/index.js"
    networks:
      - docker-rede
    environment:  
      REDIS_CONN: ${REDIS_CONN}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MONGO_CONN: ${MONGO_CONN}
